routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('posts','PostController');
Route::delete('posts/{id}', 'PostController@destroy')->name('posts.destroy');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = ['title','description','price'];


}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Illuminate\Http\Request;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts=Post::all();
        return view('posts.index',compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('posts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title'=> 'required|max:255',
            'description'=> 'required|max:255',
            'price'=> 'required||max:11'
        ]);
        $post=new Post([
            'title'=>$request->get(htmlspecialchars(trim('title'))),
            'description'=>$request->get(htmlspecialchars(trim('description'))),
            'price'=>$request->get(htmlspecialchars(trim('price'))),

        ]);
        $post->save();
        return redirect('/posts')->with('success','Товар был удачно добавлен!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post=Post::find($id);
        
        return view('posts.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post=Post::find($id);
        return view('posts.edit', compact('post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title'=> 'required|max:255',
            'description'=> 'required|max:255',
            'price'=> 'required||max:11'
        ]);
        $post=Post::find($id);
        $post->title=$request->get('title');
        $post->description=$request->get('description');
        $post->price=$request->get('price');
        $post->save();

        return redirect('/posts')->with('success','Данные о товаре были успешно отредактированы!');

        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    // public function destroy($id)
    // {
    //     $post=Post::find($id);
    //     $post->delete();

    //     
    // }
    public function destroy($id){
        $post = Post::find($id);
        $post->delete();
         return response()->json([
          'message' => 'Data deleted successfully!'
         ]);
        //return redirect('/posts')->with('success','Товар был успешно удален!');

    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="{{ asset('css/app.css')}}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <title>@yield('title')</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-success mb-2">
    <div class="container">

  <a class="navbar-brand" href="#">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{route('posts.index')}}">Products</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
      </div>

</nav>
    <div class="container">
    @yield('content')
    </div>
    <script src="{{asset('js/app.js')}}"></script>
    <script>
    $(function()
    {
      $('.alert-success').fadeOut(2500);
    });
    </script>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')
@section('title', 'Добавить новый товар')

@section('content')
<div class="row">
<div class="col-lg-6 mx-auto">
@if($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif
<form method="POST" action="{{ route('posts.store') }}">
  @csrf
  <div class="form-group">
    <label for="item-title">Наименование товара</label>
    <input type="text" value="{{old('title')}}" class="form-control" id="title" placeholder="Apple IPHONE X" name="title" >
  </div>
  <div class="form-group">
    <label for="item-description">Описание товара</label>
    <textarea name="description" class="form-control" id="description" rows="3" >{{old('description')}}</textarea>
  </div>
  <div class="form-group">
    <label for="item-price">Цена за единицу товара</label>
    <input type="number"value="{{old('price')}}" class="form-control" id="price" placeholder="X $" name="price" >
  </div>
  <button type="submit"class="btn btn-success">Добавить товар</button>
  </div>
  </div>
</form>
@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')
@section('title',$post->title)

@section('content')
<div class="row">
<div class="col-lg-6 mx-auto">
@if($errors->any())
<div class="alert alert-danger">
  <ul>
    @foreach($errors->all() as $error)
    <li>{{$error}}</li>
    @endforeach
  </ul>
</div>
@endif
<form method="POST" action="{{ route('posts.update',$post) }}">
  @csrf
  @method('PATCH')
  <div class="form-group">
    <label for="item-title">Наименование товара</label>
    <input type="text" value="{{$post->title}}" class="form-control" id="title" placeholder="Apple IPHONE X" name="title" >
  </div>
  <div class="form-group">
    <label for="item-description">Описание товара</label>
    <textarea name="description" class="form-control" id="description" rows="3" >{{$post->description}}</textarea>
  </div>
  <div class="form-group">
    <label for="item-price">Цена за единицу товара</label>
    <input type="number"value="{{$post->price}}" class="form-control" id="price" placeholder="X $" name="price" >
  </div>
  <button type="submit"class="btn btn-success">Отредактировать</button>
  </div>
  </div>
</form>
@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('title', 'Все посты')
@section('content')
<body>
<a href="{{route('posts.create')}}"class="btn btn-success">Добавить новый товар</a>
@if(session()->get('success'))
<div class="alert alert-success mt-3">
  {{session()->get('success')}}
</div>
@endif
<table id="data_table" class="table table-striped table-dark mt-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Наименование</th>
      <th scope="col">Описание</th>
      <th scope="col">Цена</th>
      <th style="text-align: center;" scope="col">Действия</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
      @foreach($posts as $post)
    <tr>
      <th scope="row">{{$post->id}}</th>
      <td>{{$post->title}}</td>
      <td>{{$post->description}}</td>
      <td>{{$post->price}}</td>
      <td class="table-buttons">
          <a href="{{ route('posts.show', $post) }}"class="btn btn-success">
          <i class="fa fa-eye"></i>
          </a>
          <a href="{{ route('posts.edit',$post) }}" class="btn btn-primary">
          <i class="fa fa-pencil"></i>
          </a>
            @csrf
            @method('DELETE')
          <button data-id="{{ $post->id }}"  type="submit" class="btn btn-danger" id="deleteProduct"> 
          <i class="fa fa-trash" ></i>
          </button>
      </td>
    </tr>
    @endforeach     
  </tbody>
</table>
<script>
$(document).ready(function () {

$("body").on("click","#deleteProduct",function(e){

   if(!confirm("Вы действительно хотите удалить?")) {
      return false;
    }

   e.preventDefault();
    var id = $(this).attr('data-id');
   var token = $("meta[name='csrf-token']").attr("content");
   var url = e.target;

   $.ajax(
       {
         url:"posts/"+id, 
         type: 'DELETE',
         data: {
           _token: token,
               id: id
       },
       success: function (response){
           $("#success").html(response.message)

           Swal.fire(
             'Good!',
             'Product deleted successfully!',
             'success'
           )
           location:reload();
       }
    });
     return false;
  });
  
});
</script>
</body>
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('title',$post->title)

@section('content')
<div class="card">
    <div class="card-body">
        <h2>{{$post->title}}</h2>
        <p>{{$post->description}}</p>
        <p><strong> Цена :{{$post->price}}$</strong></p>
    </div>
</div>
@endsection